###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: symfonypetshop-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=dev123
        - MYSQL_DATABASE=symfonypetshop
        - MYSQL_USER=julio
        - MYSQL_PASSWORD=dev123
      ports:
        - "8002:3306"

    webserver:
      image: nginx:alpine
      container_name: symfonypetshop-webserver
      working_dir: /application
      volumes:
          - ./petshop:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8000:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: symfonypetshop-php-fpm
      working_dir: /application
      volumes:
        - ./petshop:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

